### ISSUE TITLE
StreamFX 0.12 causes OBS 29.0.0 to hang on exit on Linux

### ISSUE THREAD

**Issue by flexiondotorg** [Xaymar/obs-stream-effects#1017]
### OBS Studio Logs

 - https://obsproject.com/logs/GBfWOOx3ZFP4ZVzB

### Current and Expected Behavior

Many thanks for StreamFX, it is an extremely valuable addition to OBS Studio 🙇

I build OBS Studio from source, along with a collection of plugins, in a clean container for Ubuntu 22.04 with `-DLINUX_PORTABLE=ON` using GCC 11.3.0.  StreamFX 0.12 is included and built in-tree. I noticed that OBS was hanging on exit and it appeared to be StreamFX that was halting shutdown while unloading.

```
info: [obs-websocket 4.9.1-compat] IO thread exited.
info: [obs-websocket 4.9.1-compat] Server stopped successfully.
info: [adv-ss] trying to reconnect to  in 10 seconds.
info: [adv-ss] trying to reconnect to  in 10 seconds.
info: [StreamFX] Unloading Version 0.12.0a168-g07d4e0ab
info: [StreamFX] <gfx::opengl> Finalized.
```

Does not progress past that 👆 point, so Ctrl+C is issued

```
^Cfish: Job 1, './obs-portable' terminated by signal SIGSEGV (Address boundary error)
```

StreamFX 0.12.0a151 was the first tagged pre-release that exhibited the issue, and after some debugging this commit introduced the change in behaviour:

  - https://github.com/Xaymar/obs-StreamFX/commit/7e234c6c4bf649de455eeeb34794fa9928eea1cd

Video Cards:
    Driver:  AMD Radeon RX 6700 XT (navy_flounder, LLVM 13.0.1, DRM 3.42, 5.15.0-58-generic)
    Driver Version:  4.6 (Compatibility Profile) Mesa 22.0.5
    OpenGL Version: 4.6
    For NVENC encoding only: NVIDIA Corporation TU117GL [T1000 8GB] (rev a1)

Operating System Version:
    Ubuntu 22.04.1 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  5.15.0-58-generic

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen Threadripper 3970X 32-Core Processor
    CPU Family:  0x17
    CPU Model:  0x31
    CPU Stepping  0x0
    CPU Type:  0x0
    Speed:  4549 Mhz
    64 logical processors
    32 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported

### Steps to Reproduce the Problem

Build OBS Studio 29.0.0 with StreamFX [0.12.0b164](https://github.com/Xaymar/obs-StreamFX/tree/0.12.0b164) include in-tree on Ubuntu 22.04.1.

 - Start OBS Studio in a terminal
 - Complete the startup wizard
 - Exit OBS Studio, it will not cleanly exit

### Any additional Information we need to know?

Behaviour introduced via https://github.com/Xaymar/obs-StreamFX/commit/7e234c6c4bf649de455eeeb34794fa9928eea1cd

From a discussion on Discord, this might be a Threadripper-related issue.

**Comment by flexiondotorg** [comment]
OK, dirty workaround in place. I have made a build that includes StreamFX from the tip of git https://github.com/Xaymar/obs-StreamFX/commit/07d4e0ab3f7f892cddfb14b5642b9f922e492d6c but reverts https://github.com/Xaymar/obs-StreamFX/commit/7e234c6c4bf649de455eeeb34794fa9928eea1cd

This gets me a local build that "works", and unblocks me while I help investigate this issue.

**Comment by Xaymar** [comment]
Don't seem to have a repro on my Ubuntu 22.04 machine. Would need the gdb backtrace of the stuck threads to somewhat figure out whats going on.

**Comment by Xaymar** [comment]
#### Rejected: Inactivity / Unable to repro
With the information provided, I have so far been unable to reproduce this issue on a clean installation of Ubuntu 22.04. None of my systems encounter this issue. Additionally even thigh more data was requested, none was provided. Therefore closing.

**Comment by flexiondotorg** [comment]
It was suggested in our Discord conversation that this might be due to Threadripper, however, the same issue is observed using non-Threadripper too.

```
20:54:56.220: Command Line Arguments: --portable
20:54:56.220: Using EGL/X11
20:54:56.220: CPU Name: Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
20:54:56.220: CPU Speed: 4100.807MHz
20:54:56.220: Physical Cores: 6, Logical Cores: 6
20:54:56.220: Physical Memory: 15921MB Total, 4314MB Free
20:54:56.220: Kernel Version: Linux 5.19.0-1015-lowlatency
20:54:56.221: Distribution: "Ubuntu" "22.10"
20:54:56.221: Session Type: x11
20:54:56.221: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
20:54:56.221: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled)
20:54:56.221: Portable mode: true
20:54:56.262: OBS 28.1.0-rc1-modified (linux)
20:54:56.262: ---------------------------------
20:54:56.293: ---------------------------------
20:54:56.293: audio settings reset:
20:54:56.293:     samples per sec: 48000
20:54:56.293:     speakers:        2
20:54:56.293:     max buffering:   960 milliseconds
20:54:56.293:     buffering type:  dynamically increasing
20:54:56.302: ---------------------------------
20:54:56.302: Initializing OpenGL...
20:54:56.327: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
20:54:56.327: OpenGL loaded successfully, version 3.3.0 NVIDIA 510.108.03, shading language 3.30 NVIDIA via Cg compiler
20:54:56.350: ---------------------------------
```

I am working on creating a debug build that I can share with you to help understand the root cause, but my time is limited.

**Comment by Xaymar** [comment]
Unless it happens with the official binaries, there isn't anything i can make use of with your debug binaries. I need a stack trace to even have an idea at what is causing the issue.

**Comment by flexiondotorg** [comment]
This can remain closed, as I have identified the root cause, and I think it can be filed under "I was holding it wrong".

I was building with `-DStreamFX_ENABLE_FRONTEND=OFF` and putting the obs-StreamFX source in `UI/frontend-plugins` (👈 mistake). With this combination, the lock-up on exit is observed.

I am now correctly putting the obs-StreamFX source in `plugins` while continuing to build with `-DStreamFX_ENABLE_FRONTEND=OFF`, and all is well.

**Comment by flexiondotorg** [comment]
I have discovered the root cause of the issue; it seems there is some kind of incompatibility with [Source Dock](https://github.com/exeldro/obs-source-dock) and StreamFX plugins being installed at the same time since https://github.com/Xaymar/obs-StreamFX/commit/7e234c6c4bf649de455eeeb34794fa9928eea1cd

If I remove the Source Dock plugin and keep StreamFX, then OBS 29.0.0 exits cleanly.

**Comment by Xaymar** [comment]
I still need a stack trace, which should be easy to provide.
