### ISSUE TITLE
Blur effect not showing up in OBS filters. How do I install the plug-ins?

### ISSUE THREAD

**Issue by siefors** [Xaymar/obs-stream-effects#11]
Hello Xaymar, could you please help me by telling me how to install the plug-ins? I tried placing the files in both "C:\Program Files\OBS\plugins" and "C:\Program Files (x86)\OBS\plugins" folders but still no luck. I can't get the blur filter to show up in OBS. I'm using OBS 21.0.1 (64bit, windows).

Greetings

**Comment by Xaymar** [comment]
Unpack in the installation directory of obs-studio, not any subdirectory. That means if you installed OBS Studio to C:\Program Files\obs-studio you extract it into there. It's easy to tell if you did it right because the directory structure in the archive is the same as the one obs-studio installs.

**Comment by siefors** [comment]
OMG it works! Thank you SO much I have been scouring the internet the past time looking for ways to make this work. Wow I should've posted my question here much earlier. Thanks again! Cheers.

**Comment by RuinedYourLife** [comment]
So I have extracted the rar to the root folder of OBS and it doesn't work. Any solution please ^^

**Comment by hesa2020** [comment]
Having the same issue, however copied to the right location, using OBS 21.0.1 ( Windows )

Copied to
`C:\Program Files (x86)\obs-studio`

both `data` and `obs-plugins`

**Comment by 1v4r** [comment]
Hello. Some install issues:

```
Windows Version: 10.0 Build 18362 (release: 1903; revision: 720; 64-bit)
--
10:13:15.827: OBS 25.0.1 (64-bit, windows)
--
10:13:17.491: LoadLibrary failed for '../../obs-plugins/64bit/StreamFX.dll': (null) (126)
10:13:17.491: Module '../../obs-plugins/64bit/StreamFX.dll' not loaded
```

Any help would be great. thanks :D

**Comment by Xaymar** [comment]
Install the VCRedist as outlined in the Wiki article "Installation"

**Comment by mxkris** [comment]
Sorry to bring this back from the dead but I am having issues with blur (and the others, as well as the new transitions) not showing up in OBS. There are some new elements that appear but not nearly all of them. There is also a StreamFX menu in the menu-bar.

I have the vcredist installed and in my log it shows that it is loading the StreamFX.dll without error.

Please let me know if there is any other info I can provide to help sort this out.

StreamFX 0.8.0
OBS Studio 25.0.8
```22:17:37.667: [StreamFX] Loading Version 0.8.0.0-e343e4cb
22:17:37.684: [StreamFX] <NVIDIA Face Tracking Filter> Failed to load Nvidia AR SDK runtime.
22:17:37.749: [StreamFX] Loaded Version 0.8.0.0-e343e4cb```

**Comment by skeletonbow** [comment]
@mxkris The #help-and-support channel on Xaymar's discord if you need assistance troubleshooting problems you're having installing or using StreamFX.  Bug reports here aren't the place to seek technical support however, in particular randomly adding them to already closed bug reports.

**Comment by Xaymar** [comment]
Additionally please open your own issues, instead of "bringing things back from the dead".
