### ISSUE TITLE
Blur Filter: Allow only blurring a region of the image

### ISSUE THREAD

**Issue by NoxNebula** [Xaymar/obs-stream-effects#12]
Make it possible to not just blur the whole source. The ability to make a selection there the blur filter is applied on the source.

**Comment by Xaymar** [comment]
To clarify, do you want this to be a hard cut or have an option for smoothing out? If latter, I have to write a bit more code but it will work.

**Comment by NoxNebula** [comment]
Nice to hear you working on it 😃. I was thinking of a hard cut, but an option to smooth it would be a good idea too (although I personally wouldn't use this feature).

**Comment by Xaymar** [comment]
Work in progress, this is a test of the region select code on the GPU itself.

![image](https://user-images.githubusercontent.com/437395/39395950-dcfb3082-4ae5-11e8-81cc-3b54857857fe.png)
![image](https://user-images.githubusercontent.com/437395/39395958-ebde4972-4ae5-11e8-965e-34bc4cb05a3f.png)

**Comment by Xaymar** [comment]
Semi-finished product for Box Blur
![image](https://user-images.githubusercontent.com/437395/39396258-1dd1df3e-4aeb-11e8-82d1-133e4015bf77.png)

**Comment by NoxNebula** [comment]
Wow, this really looks promising.
I assume the "Filter.Blur.Region.Feather" is a setting for the edge smoothness?
Secondly I want to ask if the filter will work on a game capture, like the non-region version?

Keep up the good work. 👍

**Comment by Xaymar** [comment]
All Filters work on any kind of source, they really have no reason to not work on a specific source. Yes "Filter.Blur.Region.Feather" is the "edge smoothness" or usually known by feather area.

**Comment by Xaymar** [comment]
And here is the final result, all three types of blur can now be selectively applied to a region or the inverse of that region, with an optional feather area.

![image](https://drive.google.com/uc?id=1QxCcBwniVJHHJaI-TJ-t7NTLniHPXFgb)
![image](https://user-images.githubusercontent.com/437395/39401285-a6ec4d9e-4b41-11e8-8574-8fee6448124e.png)
