### ISSUE TITLE
Linux and MacOS Standalone Builds

### ISSUE THREAD

**Issue by aliksend** [Xaymar/obs-stream-effects#13]
Hi

Thank you for your library.
How difficult is it to compile it for OS X and linux? 
I tried to compile it on my mac and got error:
```
CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:obs-stream-effects>

  TARGET_PDB_FILE is not supported by the target linker.
```
I think that some platform-specific build configuration required like in obs-studio `CMakeLists.txt`. But is configuration will be enough or there is some windows-specific code in your library that makes cross-platform more complex?

Thank you

**Comment by Xaymar** [comment]
As far as I know, there is no code that makes it incompatible with other platforms. Standalone builds however currently require Windows, as you have already discovered.

**Comment by aliksend** [comment]
As I understood you will make builds for mac and linux. Thanks, I will wait for it.

**Comment by Xaymar** [comment]
After three years, StreamFX is now natively available on both platforms.
