### ISSUE TITLE
Blur Filter allow a bluring map/mask

### ISSUE THREAD

**Issue by NoxNebula** [Xaymar/obs-stream-effects#14]
I have a great idea (in my opinion). In addition to restricting the blur to a region #12. I think it would be really useful and should provide everything what you possibly could need for setting a region to blur (On the condition that this would be possible).

I thought of an image (mask) like the displacement map, there are "pixels" set which would blur and which are not. Like ***white* for 100%** and ***black* for 0%** blur (speak: no blur). I'm not quite sure if it should include the shades of gray for setting something like 50% blur (Like a manual feather).

---

![Blur mask example](https://i.imgur.com/HzDFy6n.png)

---

This image would be for a 1920x1080 canvas. It maybe should be possible to scale the mask/map up or down for different canvas sizes.

I'm not really in image processing, that's why I can't judge how possible this is. But I thought this would be a handy idea which would serve a solution for every purpose you could possibly need for setting a region.

Tell me what do you think about this.

**Comment by Xaymar** [comment]
This will be implemented in a different way - you will be able to use a different source as an input for the mask and select the channels to use for the blur mask.

**Comment by NoxNebula** [comment]
That is awesome, and you too 👍
