### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by EMTGuy777** [Xaymar/obs-stream-effects#15]
Hi Xaymar. I am having some issues with downloading OBS stream effects. I've read through a few comments made to you, saw your responses, and tried to follow them. I unpacked it in the installation studio of OBS-studio but still not getting it to work. 
![obs file path](https://user-images.githubusercontent.com/20566239/45268434-426fc180-b44a-11e8-8d08-1d5830894f0a.png)

Is there something I am missing here? Thanks for your time.

**Comment by Xaymar** [comment]
Future builds will include an installer, just like obs-amd-encoder does.
