### ISSUE TITLE
Crushing Problem

### ISSUE THREAD

**Issue by pfdundar** [Xaymar/obs-stream-effects#19]
When I copy and paste this plugin OBS crushes every time. I cannot even open the program

**Comment by Xaymar** [comment]
Please fill out the following information:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Operating System: [e. g. Windows, Debian, Ubuntu, ...]
 - Kernel Version: [e.g. 1809 (Windows), 4.12 (Linux]
 - Plugin Version: [e.g. 0.4.2, 0.5.0preview 1]

**Additional context**
Add any other context about the problem here.
```

**Comment by pfdundar** [comment]
1. Go to 'C:\Program Files\obs-studio\obs-plugins\64bit'
2. Paste the plugin: 'obs-stream-effects.dll' and 'obs-stream-effects.pdb' (64 bit)
3. Click OBS from desktop
4. See this error 'obs has crushed'
I use windows 10
plugin version: 0.4.2

is it enough?

**Comment by Xaymar** [comment]
Yes, it shows that you didn't install the plugin correctly. The plugin also requires the data it is packaged with, which you have to unpack into the correct places. The .zip and .7z files **match the OBS Studio installation structure**, so you extract the entire plugin into your obs-studio installation.
