### ISSUE TITLE
Building as plugin on Linux: templates with C linkage

### ISSUE THREAD

**Issue by catb0t** [Xaymar/obs-stream-effects#27]
**Describe the bug**

>**Xaymar commented on Apr 26, 2018** 
> Standalone builds however currently require Windows, as you have already discovered. So in order to build it on Linux and Mac, you need to include it as a plugin in obs-studio.

Does that mean that on Linux, I have to compile this as part of an obs-studio build? 
 
I'm compiling directly on Ubuntu (not part of an OBS build), and I **don't** get [@aliksend's error](https://github.com/Xaymar/obs-stream-effects/issues/13#issue-317734482): 
```
CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:obs-stream-effects>

  TARGET_PDB_FILE is not supported by the target linker.
```

instead it's some mixing-up of C and C++ headers / code

https://gist.github.com/catb0t/a0ef26bd65612ec1f220579f9e609fc9

the first main error is 
``` 
In file included from /usr/include/c++/8/chrono:40,
                 from /home/cat/Downloads/obs-stream-effects/source/filter-blur.h:24,
                 from /home/cat/Downloads/obs-stream-effects/source/plugin.cpp:21:
/usr/include/c++/8/limits:317:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return _Tp(); }
           ^
```
the other one, which is repeated the most, is 

```
In file included from /usr/include/c++/8/bits/move.h:55,
                 from /usr/include/c++/8/bits/stl_function.h:60,
                 from /usr/include/c++/8/functional:49,
                 from /home/cat/Downloads/obs-stream-effects/source/plugin.h:21,
                 from /home/cat/Downloads/obs-stream-effects/source/strings.h:21,
                 from /usr/include/string.h:431,
                 from /home/cat/Downloads/obs-stream-effects/build/libobs-src/include/util/bmem.h:22,
                 from /home/cat/Downloads/obs-stream-effects/build/libobs-src/include/obs.h:21,
                 from /home/cat/Downloads/obs-stream-effects/build/source/module.cpp:1:
/usr/include/c++/8/type_traits:71:3: error: template with C linkage
   template<typename _Tp, _Tp __v>
   ^~~~~~~~
In file included from /usr/include/features.h:424,
                 from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
                 from /usr/include/stdint.h:26,
                 from /usr/lib/gcc/x86_64-linux-gnu/8/include/stdint.h:9,
                 from /home/cat/Downloads/obs-stream-effects/build/libobs-src/include/util/c99defs.h:72,
                 from /home/cat/Downloads/obs-stream-effects/build/libobs-src/include/obs.h:20,
                 from /home/cat/Downloads/obs-stream-effects/build/source/module.cpp:1:
/usr/include/string.h:28:1: note: ‘extern "C"’ linkage started here
 __BEGIN_DECLS
 ^~~~~~~~~~~~~
```
Those go on for quite some time until the build fails. 

**To Reproduce**
1. `git clone Xaymar/obs-stream-effects`
2. `mkdir build; cd build; cmake ..; make`

**Expected behavior**
Project builds. 

**Desktop**
 - Operating System: Ubuntu 18.10
 - Kernel Version: Linux 4.18.0-13-generic
- Plugin Version: 0.4.2.139 (HEAD)
- OBS Studio (system installation): 22.0.2 (linux) 
 

**Additional context**
I spent 3 hours trying to figure this out, but I can't even change the error output. I can compile other (C-source) OBS plugins and I have a working C++ compiler with C++ STL / headers. 

- commenting out `extern "C"` in `source` changes nothing 
- including `<obs/....h>` (system-wide OBS headers from `libobs-dev`) changes nothing 

It seems like this project manages to make C source files include C++ source files, while `__cplusplus` is defined, so the `extern "C"` is overridden and templates become declared with C linkage. No idea how to make it compile though.

**Comment by Xaymar** [comment]
With #28 merged, does it compile? I unfortunately have not invested much time into linux builds yet, but it would be nice if I had some steps for building to use in an automated fashion later on. (maybe even standalone if i ever figure that out)

**Comment by catb0t** [comment]
Thanks for your help on this! The commits in `linux-compatibility` help, but there are still a lot of the `template with C linkage` errors from the un-fixed files, so it doesn't compile yet.

It's closer, though. I think I can fix the rest and make a PR.

**Comment by Xaymar** [comment]
```
/mnt/d/Projects/OpenBroadcasterSoftware/obs-studio/plugins/obs-stream-effects/source/filter-transform.hpp:83:34: error: member ‘std::unique_ptr<util::vec3a> filter::Transform::Instance::<unnamed struct>::rotation’ with constructor not allowed in anonymous aggregate
     std::unique_ptr<util::vec3a> rotation;
```
last error, and I have no idea what that even means.

**Comment by catb0t** [comment]
Thank you, I think I can fix that one and the rest of these to get it to compile with Clang++

**Comment by Xaymar** [comment]
Success! 🎉 obs-stream-effects successfully built inside of the ubuntu shell in Windows 10:

```
[ 96%] Linking CXX shared module obs-stream-effects.so
[100%] Built target obs-stream-effects
```

There is a ton of warnings (due to -Wpedantic and obs using anonymous structs), but it does compile!

**Comment by catb0t** [comment]
Whether I point to your `libobs` or the "official" one: 
```
/home/cat/Sync/projects/git/obs-stream-effects/build/libobs-src/include/graphics/../util/base.h:46:2: fatal error: redefinition of
      enumerator 'LOG_ERROR'
        LOG_ERROR   = 100, 
        ^
/usr/include/obs/util/base.h:46:2: note: previous definition is here
        LOG_ERROR   = 100, 
        ^
```

Even if you could add a named include guard (`#ifdef LIBOBS_UTIL_BASE ... #endif`) to `libobs`, it would have to be a named one in `<obs/obs.h>` too, maybe that's not a bad idea?

**Comment by Xaymar** [comment]
That would be something for obs-studio, not obs-stream-effects. It seems that Clang++ is fighting over something defined in literally the same file, which gcc does not do.

**Comment by Xaymar** [comment]
See new branch clang-compatibility for additional fixes.

**Comment by catb0t** [comment]
Oh, I started using clang++ for this after I saw the [GCC bug](https://stackoverflow.com/questions/25594644/warning-specialization-of-template-in-different-namespace), but with `CMAKE_CXX_COMPILER=g++`
```
In file included from /home/cat/Sync/projects/git/obs-stream-effects/build/libobs-src/include/util/bmem.h:20,
                 from /home/cat/Sync/projects/git/obs-stream-effects/build/libobs-src/include/graphics/graphics.h:20,
                 from /home/cat/Sync/projects/git/obs-stream-effects/source/gs-texture.hpp:28,
                 from /home/cat/Sync/projects/git/obs-stream-effects/source/gs-rendertarget.hpp:23,
                 from /home/cat/Sync/projects/git/obs-stream-effects/source/gfx-source-texture.hpp:21,
                 from /home/cat/Sync/projects/git/obs-stream-effects/source/filter-blur.hpp:29,
                 from /home/cat/Sync/projects/git/obs-stream-effects/source/plugin.cpp:21:
/home/cat/Sync/projects/git/obs-stream-effects/build/libobs-src/include/util/base.h:46:16: error: ‘LOG_ERROR’ conflicts with a previous declaration
  LOG_ERROR   = 100,
                ^~~
```

**Comment by Xaymar** [comment]
You might have to use:
```
CC=/usr/bin/clang
CXX=/usr/bin/clang++
```
instead (replace /usr/bin with wherever your clang is at). I have successfully compiled obs-studio with clang this way.

**Comment by catb0t** [comment]
Awesome, it builds for me with any compiler on `clang-compatibility`!

**Comment by Xaymar** [comment]
Nice! I've moved tracking of remaining warnings to #29.
