### ISSUE TITLE
15 Memory leaks without source mirrors 

### ISSUE THREAD

**Issue by catb0t** [Xaymar/obs-stream-effects#33]
**Describe the bug**
Separate to #32 (I think), I'm not using any source mirrors that I'm aware of but OBS reports 15 memory leaks when exiting with the plugin loaded 

**To Reproduce**
1. Stop the plugin from loading
2. See OBS exit with 0 memory leaks 
3. Make the plugin loaded by OBS again
4. See OBS exit with 15 memory leaks

**Expected behavior**
No leaks.

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 18.10
 - Kernel Version: Linux 4.18
 - Plugin Version: f910312a2d50ff236d6fd77c0badcf9fefd57729

I'll look into debugging this with Valgrind / ASAN at some point.

**Comment by catb0t** [comment]
That was with OBS 22.0.2, I just built OBS from source and now i get 42 memory leaks with Stream effects loaded.

**Comment by Xaymar** [comment]
9848c5a adds proper move and copy constructors and operators to obs::source. There's likely more places where this is needed.

**Comment by Xaymar** [comment]
Can you try and isolate from which source these are coming from? Add a `return` statement before obs_register_source for each source and filter until you find the problematic source.

**Comment by Xaymar** [comment]
Source Mirror is now leak free.

**Comment by Xaymar** [comment]
Fixed bugs and leaks in Transform Filter too now.

**Comment by catb0t** [comment]
With only an `Inner/Outer Shadow` filter on an image source, I see 12 memory leaks, this patch makes it have 0: 

```
diff --git a/source/filter-shadow-sdf.cpp b/source/filter-shadow-sdf.cpp
index 02178aa..c03c7ed 100644
--- a/source/filter-shadow-sdf.cpp
+++ b/source/filter-shadow-sdf.cpp
@@ -406,6 +406,7 @@ void filter::shadow_sdf::shadow_sdf_factory::destroy(void* inptr)
        if (get()->sources.empty()) {
                get()->on_list_empty();
        }
+       delete ptr;
 }
 
 void filter::shadow_sdf::shadow_sdf_factory::get_defaults(obs_data_t* data)
```

But, I don't understand how `destroy` is called, so I don't know if the caller should actually be deleting that pointer rather than `destroy`.

**Comment by catb0t** [comment]
I haven't tested any other filters but I think that fixed all the leaks I was seeing.
