### ISSUE TITLE
Barrel Distortion of Sources

### ISSUE THREAD

**Issue by mheyman89** [Xaymar/obs-stream-effects#54]
**Is your feature request related to a problem? Please describe.**

I want to emulate the perceived distortion of viewing an image on old, curved CRT monitors.

**Describe the solution you'd like**

I would like the ability to apply this distortion to a video source with separate inputs for the x and y axes. It would be ideal to be able to apply the distortion after things like scaling and cropping.

Information on the distortion algorithm can be found here:
https://stackoverflow.com/questions/6199636/formulas-for-barrel-pincushion-distortion
http://sprg.massey.ac.nz/pdfs/2003_IVCNZ_408.pdf

**Describe alternatives you've considered**

I've considered using a displacement filter to simulate this look but the results haven't been as desirable and as easy to iterate as simple numerical inputs.

**Additional context**

https://publiclab.org/system/images/photos/000/021/421/large/Screen_Shot_2017-08-25_at_11.40.41_AM.png

The image on the left is the result I am trying to achieve. The image on the right would be the original source.

**Comment by Xaymar** [comment]
You can implement this using the Shader filter in 0.7.1 now.

**Comment by Xaymar** [comment]
Custom Shaders are completely capable of this, though scripting the inputs may not be supported for a while.
