### ISSUE TITLE
Blending modes for scenes 

### ISSUE THREAD

**Issue by fatihG** [Xaymar/obs-stream-effects#56]
Would be great if scenes could be layered additively or multiplicatively 

Similar to photoshops Screen, Multiply, Overlay, etc. blending modes.

**Comment by Xaymar** [comment]
Do you mean as a filter to add additional sources & scenes on top of sources & scenes?

**Comment by fatihG** [comment]
Sorry for the late reply. 

But, exactly. 
Say I have my capture source. 
I want to put a video media source or an image source on top that is set to 'additive'. 
I find that simply have a transparency effect doesnt cut it if I want to create some special effects. 


For example if I wanted to fake a 'bloom' effect. 
- mirror source >apply some image correction (isolation the brightest parts of the image) > apply a blur filter to it. And set the entire source to be additive.
- capture source.

**Comment by Xaymar** [comment]
From what I understand of your request, it is impossible without changing the frame of the request. OBS Studio does not have any normal layering that can be affected by the plugin, so this would have to be an OBS Studio feature request - in which case you're on the wrong project entirely.

But if we do change the frame of the request, this is not impossible, but it will have to be a filter. Filters are the only thing that can safely render on top of another thing while also knowing what's below it.

**Comment by fatihG** [comment]
I mean even as a filter, is it possible for the filter to make the source additive? 
Like for example you can set opacity through a filter, right?
Could it be possible to have a setting in a filter that lets you choose between additive, multiply, overlay, etc.?

**Comment by Xaymar** [comment]
Yes, it would be possible to have that as a filter.

**Comment by Xaymar** [comment]
![image](https://user-images.githubusercontent.com/437395/58442297-36b45000-80ea-11e9-95fc-f44c98024cf3.png)

This is technically already possible with the Dynamic Mask filter.

**Comment by fatihG** [comment]
Nice! 
The bloom example was just that... an example of how an additive effect could be used.

Allot of times I try to get a glow effect or whatever on a scene, but simply have a .png doesnt sell the idea of a glow. if that makes sense.

**Comment by Xaymar** [comment]
Dynamic Mask Filter is out in the latest plugin, essentially implementing this feature.

**Comment by UnaiM** [comment]
Hi @Xaymar,

Could you explain how that additive effect is achieved using the Dynamic Mask filter? I can’t get that result since everything is eventually multiplied by the input colour.

Thanks in advance!

**Comment by Xaymar** [comment]
It is not additive, as you already saw. If you want true additive blending, your only option is Shaders.

**Comment by UnaiM** [comment]
Oh okay, thanks a bunch for clarifying!

**Comment by UnaiM** [comment]
Thanks for your quick reply. Regarding [what you mentioned on 2019/05/28](https://github.com/Xaymar/obs-StreamFX/issues/56#issuecomment-496321702), does that simply not apply anymore?

**Comment by Xaymar** [comment]
No, and even back then it did not apply. There are no blending filters or modes integrated into StreamFX other than multiplicative mask, which works for bloom, but is limited in its applications. Shaders are the only way to do it, and I've released a number of shaders on the official Discord.

**Comment by UnaiM** [comment]
Nice, will check them out. Thanks again!
