### ISSUE TITLE
Additional Blur Types

### ISSUE THREAD

**Issue by Xaymar** [Xaymar/obs-stream-effects#6]
I'd like to see the following additional blur type in the future:

### Radial Blur
This type of blur is basically just rotating the original source around the center or another point. It creates the effect that you get when you rotate a camera around the axis of the lens.

### Zoom Blur
A type of blur that looks like forward motion is happening due to being stronger on the edges than the center.

### Directional Blur
A type of blur that looks like directional motion (X, Y).

**Comment by siefors** [comment]
Hello Xaymar, could you please help me by telling me how to install the plug-ins? I tried placing the files in both "C:\Program Files\OBS\plugins" and "C:\Program Files (x86)\OBS\plugins" folders but still no luck. I can't get the blur filter to show up in OBS. I'm using OBS 21.0.1 (64bit, windows).

**Comment by Xaymar** [comment]
@siefors Please create your own issue if you need help, this issue is for improvements to the Blur filter.

**Comment by Xaymar** [comment]
Directional Blur has been implemented in 0.5.0.

**Comment by Xaymar** [comment]
All three Blur types are now supported in 0.6.0. Will be closed when merged.
