### ISSUE TITLE
CPU Usage and Random Freezes

### ISSUE THREAD

**Issue by rhialen** [Xaymar/obs-stream-effects#68]
Hello,

when i installed Stream Effects, my OBS startes freezing every 2 seconds and also my CPU usage raised very much. After i uninstalled the Plugin, it went back to normal and i have no freezes or any high CPU usage anymore.

Any Help? Would like to use the Blur Filter, because its nice!

**Comment by Xaymar** [comment]
Do you have a log file of the problem? Also would you mind sharing the scene collection with me? You can e-mail it to info@xaymar.com, just zip up the C:\Users\YOURNAME\AppData\Roaming\obs-studio\basic\scenes directory, attach it to the email and set the subject to 68. I'll know what it's for then.

**Comment by Xaymar** [comment]
This issue will be closed in 7 days if there is no further activity.

**Comment by AnemoiThuellai** [comment]
I downloaded and installed today. And got the same thing. I uninstalled the plugin and OBS started working fine. I tried installed via the exe and then just using the zip file.

**Comment by AnemoiThuellai** [comment]
I did just get an OBS update. I tried reinstalling and the obs update did not help fix the issue.

**Comment by Xaymar** [comment]
Someone sent me a crash log for this issue. This issue does not seem to be about a crash, but about freezing and random cpu spikes (which I have been unable to repro at all).

**Comment by Xaymar** [comment]
Still unable to repro this problem at all. I do not see any sudden cpu usage spikes or random freezes.
