### ISSUE TITLE
Crash on OBS Beta

### ISSUE THREAD

**Issue by TheRealDadbeard** [Xaymar/obs-stream-effects#71]
Hy,

so I have this crash after adding a signed distance effect https://hastebin.com/eqepelabov.cpp

Then starting one time with the official one fixed it and now I can change stuff in the beta obs version.

Any ideas wth happened or the issue is?

**Comment by Xaymar** [comment]
The OBS Beta is not officially supported. Compatibility is only guaranteed with stable versions, for the sake of sanity, as there sometimes are breaking functionality or ABI changes that get reverted later on.
