### ISSUE TITLE
How to install on Linux

### ISSUE THREAD

**Issue by retnikt** [Xaymar/obs-stream-effects#72]
Sorry, I'm a bit of a newbie to this. How do I install this on Ubuntu? I've tried extracting directly in to `~/.config/obs-studio/plugins` and in to a subfolder `~/.config/obs-studio/plugins/obs-stream-filters`. What am I doing wrong?
Ubuntu 18.04, OBS Studio 23.2.1 64-bit

**Comment by Xaymar** [comment]
You have to build the plugin with your own obs-studio version on Linux. There are no pre-built Linux archives, as there has been very little progress on that front, aside from getting it to build.

**Comment by retnikt** [comment]
So how do I build it? There is no Makefile and I'm not too familiar with
cmake.

**Comment by Xaymar** [comment]
For OBS Studio, see [this guide: https://obsproject.com/wiki/install-instructions#linux-build-directions](https://obsproject.com/wiki/install-instructions#linux-build-directions). Adding the plugin is as simple as adding a git submodule to the plugins directory, and updating the CMakeLists.txt to include to the plugin source.

Alternatively, an easier way would be to pay someone to figure out the linux stuff. I'm sure there are people on the OBS Forum that know more Linux-fu than I do, as my main operating system for the time being is still Windows.

**Comment by retnikt** [comment]
Ohhh... I had no idea you had to recompile OBS. I was trying to build it
directly. Unless there is a way to do this directly? I saw #30 and inferred
there was, but is that not the case?

**Comment by Xaymar** [comment]
There is a way to build the plugin separately from OBS Studio, but it still requires the obs studio source code to work, and of course a built obs studio for the linking information. The obs project itself does not ship any prebuilt versions of those, so the windows builds automatically source it from my fork of obs studio.

**Comment by retnikt** [comment]
Ok, I guess I'll build it the other way.

**Comment by 4ntibala** [comment]
did u succeed with the build?

**Comment by retnikt** [comment]
Actually I couldn't be bothered. I streamed over the local network (
https://obsproject.com/forum/resources/obs-studio-send-an-udp-stream-to-a-second-pc-using-obs.455/)
using VLC to my Windows box with this plugin installed there and then
streamed out from there.

**Comment by catsdgs** [comment]
I have no idea what "making" on Linux is. Could someone just build the plugin for me or something? Every other OBS plugin is very easy to install to OBS, I don't see why this one couldn't be like the others. I have OBS 23.2.1 currently.

**Comment by Xaymar** [comment]
Closing as this went a bit off-topic. If you do not know how to build obs-studio, or how to add plugins to a custom built obs-studio, I won't be able to help you. If you want "easy to install", use Windows.
