### ISSUE TITLE
Crash on filter selection

### ISSUE THREAD

**Issue by ProkopRandacek** [Xaymar/obs-stream-effects#73]
When I double click the blur filter OBS crashes (windows)

https://pastebin.com/rNT7VtTL

**Comment by Xaymar** [comment]
Full repro steps?

**Comment by Xaymar** [comment]
The next full release should catch this issue and show the actual exception in the log file instead of crashing OBS.

**Comment by Xaymar** [comment]
Will close this at the end of the year if I don't hear back with repro steps. The new builds should actually no longer have this issue anyway.

**Comment by skeletonbow** [comment]
I will test this soon as I was able to easily repro it before.  Probably sometime in the coming week, will try to get feedback soon as I can though.  Thanks for looking into the issue Xaymar and working on this!

**Comment by Xaymar** [comment]
As the code path shown in the crash log no longer exists, it is probably safe to assume that it can't happen anymore.
