### ISSUE TITLE
 Signed Distance Field Effects (Filter) Freezes OBS then crash

### ISSUE THREAD

**Issue by yehya** [Xaymar/obs-stream-effects#76]
### Description

I add the Signed Distance Field Effects (Filter) to a scene or webcam or text. OBS Immediately freezes and then I have to force close it (crash it).

### Expected Behavior

Signed Distance Field Effects (Filter) works.

### Reproduction Steps

Just try out the Signed Distance Field Effects (Filter) on many different sources and one of them should crash.

### System Information

- Software Version: Stream Effects 0.7.0, OBS 23.2.1
- Operating System: Windows 10 64 bit
- Kernel Version: 10.0 build 17134
- CPU: Intel i7-6700
- GPU: NVIDIA GTX 1070
- RAM: 16GB

### Checklist:
- [ ] I have read the contribution guidelines.
- [X ] I can reproduce the issue with the exact reproduction steps I have provided.
- [ ] The issue appears on all of my systems that can run this software.

**Comment by yehya** [comment]
[Crash 2019-08-16 04-27-29.txt](https://github.com/Xaymar/obs-stream-effects/files/3508757/Crash.2019-08-16.04-27-29.txt)

**Comment by Xaymar** [comment]
This should be fixed in the current CI build: https://ci.appveyor.com/project/Xaymar/obs-stream-effects/build/artifacts

**Comment by Xaymar** [comment]
@yehya Is this still happening? If there is no reply in ~10 days I will consider this solved.
