### ISSUE TITLE
Doesn't work with SLOBS

### ISSUE THREAD

**Issue by infowolfe** [Xaymar/obs-stream-effects#8]
Please fix. TYVM.

**Comment by Xaymar** [comment]
Not a bug with the plugin, Streamlabs OBS whitelists sources and filters, so you would have to file this in their issue tracker.

**Comment by ShadowMax** [comment]
https://ideas.streamlabs.com/ideas/SL-I-7208
https://ideas.streamlabs.com/ideas/SL-I-9788

**Comment by Xaymar** [comment]
https://ideas.streamlabs.com/ideas/SL-I-3988
https://ideas.streamlabs.com/ideas/SL-I-6061

This feature request is one of the most requested ones so far on my side. Problem is that I don't have to add anything - the plugin uses the standard libOBS API, and if Streamlabs was actually implementing it they could easily have this plugin. But they chose not to.
