### ISSUE TITLE
Filters doesn't show up in menus

### ISSUE THREAD

**Issue by Noirvent** [Xaymar/obs-stream-effects#80]
### Description

Hello. 
I tried installing OBS Stream Effect in OBS Studio 23.2.1, but the filters doesn't show up in the list of filters. I tried to install both with the exe and the zip.
[Like you can see here](https://imgur.com/cMKeMkT)
[Logs](https://obsproject.com/logs/ZtvYG2adTJNl_2pd)

### Expected Behavior

The filters should be available in the list of filter

### Reproduction Steps

1. Download OSE
2. Install it in C:\Program Files\obs-studio\
3. Launch OBS 
4. Add an image to the scene
5. Add a filter to the image. 

### System Information

- Software Version: OBS 23.3.2 / Stream Effect 0.7.1
- Operating System: Windows 10 
- Kernel Version: 1903
- CPU: Intel i7-7700K
- GPU: Nvidia GTX 1080Ti
- RAM: 16GB

### Checklist:

- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
The changelog for 0.7.1 clearly states that libobs must be 24.0.0-rc2 or newer. You are still using 23.3.2, which is not 24.0.0-rc2 or newer.

**Comment by codemann8** [comment]
Wow, no backwards compatibility for the last version of OBS that supports MP4 video playback on browser sources?
