### ISSUE TITLE
Support for OS X?

### ISSUE THREAD

**Issue by joeyfigaro** [Xaymar/obs-stream-effects#81]
### Description
I managed to get the effects content where it belongs, but all of the assets for the actual plugin itself don't seem to follow expectations for plugins on mac. I'm completely new to OBS, so it's possible I'm doing something silly, but from my understanding a plugin should have an extension of `os` 

### System Information

- Software Version: 10.14.6
- Operating System: Mac OS X
- Kernel Version: N/A
- CPU: 3.4Ghz intel core i5
- GPU: Radeon Pro 570 4GB
- RAM: 64GB 2400 MHz DDR4

### Checklist:
- [ ] I have read the contribution guidelines.
- [X] This is not a bug, crash or generic issue.

**Comment by Xaymar** [comment]
There are no official linux or mac builds. Linux builds may come in the future, but Mac builds will have to wait until someone writes the CI code for it.

As for the layout, it follows the windows layout if it's built solo, or if its built together with libobs it will use libobs to stick the content in the correct places.

**Comment by Xaymar** [comment]
1.5 years later, StreamFX now supports both.
