### ISSUE TITLE
Origin configuration for the 3D transform filter

### ISSUE THREAD

**Issue by skeletonbow** [Xaymar/obs-stream-effects#84]
### Description

A very useful feature would be to be able to configure where the origin/anchor point is in the 3D transform filter, like you can do with the OBS built in 2D transform.  This would for example make it easy to line up say... the top left corner of a source to a specific pixel in OBS, and anchor that corner, then all the other controls would be relative to that origin, making it easy to build a multi-source 3D image.

One usage case would be tesselating an OBS source into N pieces to then manually 3D transform them to a non-planar surface wrapping around something.  For example one of the many "newsroom" backgrounds from stock photo sites which show a newsroom with chroma keyed fake TV screens, some of which wrap around multiple walls and things.  By having a configurable origin it would make placing things side by side in 3D space without any gaps much easier.

Customizeable origin could be configured via x, y, z values or via a mechanism that mimics the OBS 2D transform anchoring/centering etc. controls, or perhaps both depending on which is most convenient for a given application.

Thanks for your consideration!

### Checklist:

- [x] I have read the contribution guidelines.
- [x] This feature is necessary and can't be done through other means.
- [ ] This feature does not break existing functionality.
- [ ] I am willing to hire/pay someone to implement this.

**Comment by skeletonbow** [comment]
Clarification to the above...  I'm not sure if it is "necessary" per se, but in order to have the functionality it would be needed.  :)  No idea if it would break any existing functionality but hopefully not. :)

**Comment by Xaymar** [comment]
An origin system like this would break if the source was used in multiple scenes, but it is not impossible. Are you sure you don't just want to have a Corner Pin mode instead?

**Comment by skeletonbow** [comment]
![image](https://user-images.githubusercontent.com/49483514/67887734-377e6180-fb22-11e9-8d47-a339bd13f9a5.png)

Here's an example of laying out a large number of sources and how tricky it can be to do entirely by hand.  Much easier to align one source, then attach one edge to another and rotate around the one axis and skew to adjust for example.  Not sure how easy that would be to implement but it's the crux of the idea.   I can see a billion wicked possibilities. ;P

**Comment by Xaymar** [comment]
An editor like what you've imagined is not possible with standard OBS, and outside of the scope of the plugin. Corner Pin would only give you the ability to specify the four points for the geometry, which makes matching existing geometry much easier.

**Comment by Xaymar** [comment]
As for your multi-screen example there, you'd be better off just writing a shader. 3D Transform has a certain cost added to it since it needs to write a source to a texture first.

**Comment by skeletonbow** [comment]
Yeah, I wouldn't expect a full 3D editor to be built into OBS or a simple plugin, that would perhaps be a bit ambitious to say the least hehe.  The corner pin sounds like it might do the job of simplifying things at a basic level which is most of the heavy lifting likely.

**Comment by Xaymar** [comment]
Custom Shader is a better option than shoehorning this into 3D Transform for the time being. Please make a second issue for Corner Pin mode in 3D Transform, as I will close this for tracking purposes and to keep issues related to the actual request.
