### ISSUE TITLE
Adding a 2nd blur filter to a group hangs or crashes OBS

### ISSUE THREAD

**Issue by skeletonbow** [Xaymar/obs-stream-effects#85]
### Description

When attempting to add a second Stream Effects Blur filter to an OBS source, under certain conditions it will cause the program to livelock and spin "Not Responding" forever, or in some circumstances immediately crash to desktop.

When this problem occurs, OBS may or may not have written the scene collection configuration out to disk yet.  If it did not, then all OBS scene configuration since the last clean exit is lost.  If OBS did write it out to disk, then when you restart OBS it tries to load the same scene collection and the active scene has 2 blurs which immediately causes OBS to crash again.  You have to hand edit the scene collection JSON file to remove the 2nd blur, or manually remove the scene collection from the configuration in order for OBS to be able to start without crashing.

Screenshot N/A.  I do not have a crash log as it usually live-locks "Not Responding" and does not produce a crash.  OBS will sit there hung forever until the program is forcibly terminated via Task Manager or a reboot.

### Expected Behavior

To add a second blur filter configured differently than the first one without program instability.

### Reproduction Steps

With a fresh OBS installation, a new scene collection with a single scene with a group with a single source, adding a Gaussian directional blur filter, then attempting to add a second blur filter will hang OBS and/or crash to desktop as soon as you choose Blur from the "Add filter" menu.

The above description is just a usable simplified reproduction case that triggers the problem.  The actual usage case the problem was originally discovered was a more elaborate filter chain with a blur near the start and a blur desired at the end to soften the results of the rest of the filter chain.  I created a clean setup with minimal test case to confirm reproduction.  If necessary I can do more testing to try to help narrow down more specific circumstances in which it occurs.

### System Information

- Software Version: 24.0.3
- Operating System: Windows 10 x64 1809
- Kernel Version: 1809
- CPU: Intel i7 7700HQ (laptop)
- GPU: Nvidia 1050 Ti 4GB
- RAM: 16GB

### Checklist:

- [x] I have read the contribution guidelines.
- [x] I can reproduce the issue with the exact reproduction steps I have provided.
- [x] The issue appears on all of my systems that can run this software.

**Comment by Xaymar** [comment]
I can't reproduce this behavior in 0.7.0, 0.7.1, 0.7.2 and current master with OBS Studio 24.x

**Comment by Xaymar** [comment]
This may have the same cause as #83.

**Comment by Xaymar** [comment]
Confirmed having the same cause as #83. Fixed.
